import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAdminAndTurfEntities1759612434083 implements MigrationInterface {
    name = 'AddAdminAndTurfEntities1759612434083'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "fk_review_user"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "fk_review_booking"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "fk_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_review_booking"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_date_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_status_date"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "uq_user_booking"`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP CONSTRAINT "uq_day_time"`);
        await queryRunner.query(`CREATE TABLE "admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(140) NOT NULL, "password" character varying NOT NULL, "name" character varying NOT NULL, "phone" character varying, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_051db7d37d478a69a7432df1479" UNIQUE ("email"), CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."turfs_status_enum" AS ENUM('active', 'inactive', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "turfs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_id" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "address" character varying NOT NULL, "city" character varying, "state" character varying, "zipCode" character varying, "latitude" numeric(10,8), "longitude" numeric(11,8), "phone" character varying, "images" text, "amenities" text, "status" "public"."turfs_status_enum" NOT NULL DEFAULT 'active', "opening_time" TIME NOT NULL DEFAULT '06:00:00', "closing_time" TIME NOT NULL DEFAULT '23:00:00', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ed5a2c678845e4dedeef4befecd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4655c016968a6129cec929d19b" ON "turfs" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_53af0b6783371eb312587f4d06" ON "turfs" ("status") `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "turf_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD "turf_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "turf_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "cancellation_reason" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD "turf_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_type_enum" AS ENUM('general', 'maintenance', 'promotion', 'closure')`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD "type" "public"."announcements_type_enum" NOT NULL DEFAULT 'general'`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "turf_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP COLUMN "day_type"`);
        await queryRunner.query(`CREATE TYPE "public"."pricing_day_type_enum" AS ENUM('weekday', 'weekend')`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD "day_type" "public"."pricing_day_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP COLUMN "time_slot"`);
        await queryRunner.query(`CREATE TYPE "public"."pricing_time_slot_enum" AS ENUM('morning', 'afternoon', 'evening')`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD "time_slot" "public"."pricing_time_slot_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending', 'confirmed', 'active', 'cancelled', 'completed')`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "created_by" uuid`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(140) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "settings_key_key"`);
        await queryRunner.query(`CREATE INDEX "IDX_bbd6ac6e3e6a8f8c6e0e8692d6" ON "reviews" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9409365c5a7800f2fd3ebbee4" ON "reviews" ("turf_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b537140c2958bf37a5b76a8354" ON "pricing" ("turf_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_64cd97487c5c42806458ab5520" ON "bookings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a75446f226153266937263affb" ON "bookings" ("status", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_486928bf4fa88a7f71037e9250" ON "bookings" ("turf_id", "date", "start_time", "end_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_f91a0094680ec190b2f2d4c873" ON "announcements" ("is_active", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f81cb2bffedf09a4f90b658686" ON "announcements" ("turf_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_acbdcbdebd2166f63a46b10815" ON "settings" ("turf_id") `);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "UQ_2c5773ff995ca1184399289d84c" UNIQUE ("user_id", "booking_id")`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD CONSTRAINT "UQ_15d1e0664e1895b31bff3919fe8" UNIQUE ("turf_id", "day_type", "time_slot")`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "UQ_8bf05bdd56e34b421b7ad650c50" UNIQUE ("turf_id", "key")`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c9409365c5a7800f2fd3ebbee47" FOREIGN KEY ("turf_id") REFERENCES "turfs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_bbd6ac6e3e6a8f8c6e0e8692d63" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD CONSTRAINT "FK_b537140c2958bf37a5b76a8354f" FOREIGN KEY ("turf_id") REFERENCES "turfs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "turfs" ADD CONSTRAINT "FK_4655c016968a6129cec929d19bb" FOREIGN KEY ("owner_id") REFERENCES "admins"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_64cd97487c5c42806458ab5520c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_83a0522441e2f8b821fdc377b40" FOREIGN KEY ("turf_id") REFERENCES "turfs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_f81cb2bffedf09a4f90b658686d" FOREIGN KEY ("turf_id") REFERENCES "turfs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "FK_acbdcbdebd2166f63a46b108153" FOREIGN KEY ("turf_id") REFERENCES "turfs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "FK_acbdcbdebd2166f63a46b108153"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_f81cb2bffedf09a4f90b658686d"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_83a0522441e2f8b821fdc377b40"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_64cd97487c5c42806458ab5520c"`);
        await queryRunner.query(`ALTER TABLE "turfs" DROP CONSTRAINT "FK_4655c016968a6129cec929d19bb"`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP CONSTRAINT "FK_b537140c2958bf37a5b76a8354f"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_bbd6ac6e3e6a8f8c6e0e8692d63"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c9409365c5a7800f2fd3ebbee47"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "UQ_8bf05bdd56e34b421b7ad650c50"`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP CONSTRAINT "UQ_15d1e0664e1895b31bff3919fe8"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "UQ_2c5773ff995ca1184399289d84c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acbdcbdebd2166f63a46b10815"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f81cb2bffedf09a4f90b658686"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f91a0094680ec190b2f2d4c873"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_486928bf4fa88a7f71037e9250"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a75446f226153266937263affb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64cd97487c5c42806458ab5520"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b537140c2958bf37a5b76a8354"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9409365c5a7800f2fd3ebbee4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbd6ac6e3e6a8f8c6e0e8692d6"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "settings_key_key" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "created_by" character varying`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "status" character varying NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP COLUMN "time_slot"`);
        await queryRunner.query(`DROP TYPE "public"."pricing_time_slot_enum"`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD "time_slot" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP COLUMN "day_type"`);
        await queryRunner.query(`DROP TYPE "public"."pricing_day_type_enum"`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD "day_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "turf_id"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_type_enum"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP COLUMN "turf_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "cancellation_reason"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "turf_id"`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP COLUMN "turf_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "turf_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53af0b6783371eb312587f4d06"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4655c016968a6129cec929d19b"`);
        await queryRunner.query(`DROP TABLE "turfs"`);
        await queryRunner.query(`DROP TYPE "public"."turfs_status_enum"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD CONSTRAINT "uq_day_time" UNIQUE ("day_type", "time_slot")`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "uq_user_booking" UNIQUE ("user_id", "booking_id")`);
        await queryRunner.query(`CREATE INDEX "idx_booking_status_date" ON "bookings" ("date", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_date_time" ON "bookings" ("date", "end_time", "start_time") `);
        await queryRunner.query(`CREATE INDEX "idx_review_booking" ON "reviews" ("booking_id") `);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "fk_review_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "fk_review_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
